# Generated by Django 5.1.2 on 2024-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='def_profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
