# Generated by Django 5.1.2 on 2024-12-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='def_profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
