# Generated by Django 5.1.1 on 2024-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_age_customuser_bmi_customuser_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
